### PR TITLE
Doc/transformations

### LINKED ISSUE #46: Document matrix transformations
Document and explain what are the *View Matrix*, *Model View Matrix*, etc and how they work / are used.

### PR DESCRIPTION
**Pull request by dffsa**
-> Closes #46

### CODE REVIEW

**Review by rosaqq — COMMENTED** [review]
Então deixa ver se entendi:

- Mesh -> Contém as coords dos vertices relativas à Mesh origin
- ModelMatrix -> Coords da Mesh relativas à World Origin
  (Turns local vertex coords to global vertex coords)
- ViewMatrix -> Pos / Rotation da Camera
  (Turns World coords (World origin) to a world with the Camera as it's origin)
- ProjectionMatrix -> Turns World based on Camera position into frustum

**Comment by rosaqq** [comment]
-> Closes #46

**Comment by rosaqq** [comment]
@dffsa if stonks podes dar merge por mim

**Comment by dffsa** [comment]
stonks

**Pull request merged**
